[project]
name = "code_monger"
version = "0.0.1"
authors = [
  { name="Victor Kipkemboi", email="scriptilapia@gmail.com" },
]
description = "A package for on-the-fly code generation and validation "
readme = "README.txt"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = {text = "MIT"}
license-files = ["LICEN[CS]E*"]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project.urls]
Homepage = "https://github.com/victhepythonista/code_monger"
Issues = "https://github.com/victhepythonista/code_monger/issues"